### ISSUE TITLE
footprintable

### ISSUE THREAD

**Issue by wuyuedefeng** [wuyuedefeng/blogs#12]
### 基础用法
[`footprintable`](https://github.com/rails-gems/footprintable)
```
# Gemfile
gem 'footprintable'
```
[Base Usage](https://github.com/rails-gems/footprintable#usage)

--- 

### 多数据库 eg: logs
1. create `db/logs_migrate` folder
2. edit `config/database.yml`
```yaml
# MySQL. Versions 5.5.8 and up are supported.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  host: localhost
  socket: /tmp/mysql.sock
development:
  primary:
    <<: *default
    database: moon_api_development
  logs:
    <<: *default
    database: moon_api_logs_development
    migrations_paths: db/logs_migrate
test:
  primary:
    <<: *default
    database: moon_api_development
  logs:
    <<: *default
    database: moon_api_logs_development
    migrations_paths: db/logs_migrate
production:
  primary:
    <<: *default
    username: root
    password: youjin2019
    host: mysql
    port: 3306
    database: moon_api_production
  logs:
    <<: *default
    username: root
    password: youjin2019
    host: mysql
    port: 3306
    database: moon_api_logs_production
    migrations_paths: db/logs_migrate
```
3. move `db/migrate/xxxxxxxxx_create_footprints.rb` to `db/logs_migrate`

4. run `rake db:migrate`, 如果需要指定运行primary或者logs请使用一下命令
```
rails db:migrate:primary
rails db:migrate:logs

rails db:drop:primary
rails db:drop:logs
```
