### ISSUE TITLE
Active Storage文件存储

### ISSUE THREAD

**Issue by wuyuedefeng** [wuyuedefeng/blogs#14]
### 安装
```
$ rails active_storage:install
$ rails db:migrate
```
### 使用
Model不需要再添加额外字段，直接添加如下关系就行
```ruby
has_one_attached :image  ## 一对一关系 或
has_many_attached :images  ## 一对多关系
```
在控制器里的参数保护也不需要做特殊的处理，只需要保持正常的设置就可以了。

```ruby
params.require(:project).permit(..., :image)   # 一对一关系 或
params.require(:project).permit(..., images: [])   # 一对多关系
```

### 保存位置配置 `config/storage.yml`
```
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
```

默认的test和local是保存在本地的Disk中的，local默认把文件保存在storage文件夹中，所如果我们想要把文件保存在public内，可以修改成：
```
root: <%= Rails.root.join("public/storage") %>
```
当然无论我们保存在什么位置，记得把该目录加入到`.gitignore`中。

那么在开发环境中，它是如何知道使用local配置的呢？在`config/environments/development.rb`中，我们可以看到：
```ruby
# Store files locally.
config.active_storage.service = :local
```

### 阿里云OSS
```ruby
# Aliyun 文件存储
gem 'activestorage-aliyun'
```
```yaml
# config/storage.yml
aliyun:
  service: Aliyun
  access_key_id: "LTAIwdm37jvQyxxx"
  access_key_secret: "juYPTswGjbKDZdPjdsSivpOI6xxx"
  bucket: "xxx"
  endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
  # path prefix, default: /
  path: "xxxx"
  # Bucket mode: [public, private], default: public
  mode: "public"
```
```ruby
# config/environments/production.rb
config.active_storage.service = :aliyun
```
