### ISSUE TITLE
Chrome 滚动条样式

### ISSUE THREAD

**Issue by wuyuedefeng** [wuyuedefeng/blogs#27]
```css
::-webkit-scrollbar {
    width: 8px;
    height: 8px;
}
::-webkit-scrollbar-thumb {
    background-color: #d0d0d0;
    height: 50px;
    outline-offset: -2px;
    outline: 0 solid #fff;
    -webkit-border-radius: 4px;
    border: 0 solid #fff;
}
::-webkit-scrollbar-track-piece {
    background-color: #f1f1f1;
}
```
