### ISSUE TITLE
css animation

### ISSUE THREAD

**Issue by wuyuedefeng** [wuyuedefeng/blogs#33]

**Comment by wuyuedefeng** [comment]
动画延迟 classes: `delay-200ms`, `delay-400ms`, `delay-600ms`, `delay-800ms`, `delay-1000ms`
```scss
@for $i from 1 through 500 {
  .delay-#{$i*200}ms {
    animation-delay: ($i*100) + ms;
  }
}
```
