### ISSUE TITLE
Rails多数据库支持

### ISSUE THREAD

**Issue by wuyuedefeng** [wuyuedefeng/blogs#56]
# 添加logs数据库
### 更改配置`config/database.yml`
eg:  `development`
```yaml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: service_api_development
```
to 
```yaml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  primary:
    <<: *default
    database: service_api_development
  logs:
    <<: *default
    database: service_api_logs_development
    migrations_paths: db/logs_migrate
```

### 创建 logs数据库模型基类`app/models/application_logs_record.rb`
```ruby
class ApplicationLogsRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :logs

  def method_missing(method_name, *args, &block)
    case method_name
    when /_time$/
      self.send("#{method_name}".gsub(/_time$/, '_at')).to_s
    else
      super
    end
  end
end
```

### eg: 创建用户反馈`feedback`模型
`rails g model feedback trackable:references{polymorphic} actorable:references{polymorphic} contact:string desc:text read_at:datetime`

* 移动`db/migrate/xxxxxxx_create_feedbacks.rb`到`db/logs_migrate/xxxxxxx_create_feedbacks.rb`

* 更改 `app/models/feeback`基类为`ApplicationLogsRecord` 

### 创建数据库和表
```bash
# rails db:create:primary
rails db:create:logs

# rails db:migrate:primary
rails db:migrate:logs

# rails db:drop:primary
rails db:drop:logs

# 如果要同时执行primary和logs
rails db:create
rails db:migrate
# rails db:drop
rails db:seed
```
