### ISSUE TITLE
Rails active_storage集成阿里云oss

### ISSUE THREAD

**Issue by wuyuedefeng** [wuyuedefeng/blogs#57]
* 集成`active_storage`
```
$ rails active_storage:install
```
in model
```ruby
has_one_attached :image  ## 一对一关系 或
has_many_attached :images  ## 一对多关系
```

默认`storage`以文件的形式存在服务器中
*  更改`storage`存储方式到阿里云
gemfile添加 gem[`activestorage-aliyun`](https://github.com/huacnlee/activestorage-aliyun)
```bash
# Aliyun 文件存储
gem 'activestorage-aliyun'
```
修改`config/storage.yml`文件配置：
```yaml
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

aliyun:
  service: Aliyun
  access_key_id: "LTAIwdxxxxxxxx"
  access_key_secret: "juYPTswGjxxxxxxxxxxxxxxx"
  bucket: "xxxx"
  endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
  # path prefix, default: /
  path: "moon"
  # Bucket mode: [public, private], default: public
  mode: "public"
```
配置`production`环境使用阿里云存储, 需修改环境配置文件`config/enviroments/production.rb`
```ruby
 # config.active_storage.service = :local
 config.active_storage.service = :aliyun
```

* 创建上传 controller action
`rails g controller uploader file`
```ruby
class UploaderController < ApplicationController
  def file
    blob = ActiveStorage::Blob.create_after_upload!(
        io: params[:file].tempfile,
        filename: params[:file].original_filename,
        content_type: params[:file].content_type
    )
    # 本地存储
    if ActiveStorage::Blob.service.send(:service_name) === 'Disk'
      render json: { link: url_for(blob), signed_id: blob.signed_id }, status: 200
    else # Aliyun
      render json: { link: blob.service_url, signed_id: blob.signed_id }, status: 200
    end
  end
end
```
`config/router.rb`添加路由配置
```ruby
post 'uploader/file', to: 'uploader#file'
```

--- 

* [has_one_attached](https://api.rubyonrails.org/classes/ActiveStorage/Attached/One.html)

eg: model `feedback.rb`
```ruby 
class Feedback < ApplicationLogsRecord
  # belongs_to :trackable, polymorphic: true, optional: true
  # belongs_to :actorable, polymorphic: true, optional: true
  # belongs_to :application, class_name: 'Doorkeeper::Application'
  has_one_attached :image
end
```
usage, eg:
```
Feedback.create.attach(params[:signed_id])
```

* [has_many_attached](https://api.rubyonrails.org/classes/ActiveStorage/Attached/Many.html)

eg: model `feedback.rb`
```ruby 
class Feedback < ApplicationLogsRecord
  # belongs_to :trackable, polymorphic: true, optional: true
  # belongs_to :actorable, polymorphic: true, optional: true
  # belongs_to :application, class_name: 'Doorkeeper::Application'
  has_many_attached :images
end
```

usage, eg:
```
Feedback.create(images: params[:signed_ids])
```
