### ISSUE TITLE
Docker 部署cloud-ui

### ISSUE THREAD

**Issue by wuyuedefeng** [wuyuedefeng/blogs#88]
### 配置环境
```bash
# 安装docker
$ curl -sSL https://get.daocloud.io/docker | sh
# 安装docker-compose
curl -L https://get.daocloud.io/docker/compose/releases/download/1.26.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
参考： http://get.daocloud.io/

### compiler（Node部署）
pm2 config: `ecosystem.config.js`
```javascript
module.exports = {
  "name": "cloud-component-compiler",
  "script": "./app.js",
  "cwd"   : "./",
  "log_date_format": "YYYY-MM-DD HH:mm Z",
  "instances": 2,
  "max_memory_restart": "1000M",
  "merge_logs": true,
  "exec_mode": "cluster",
  "kill_timeout" : 5000,
  "ignore_watch": ["node_modules", "logs", "public"],
  "watch_options": {
    "followSymlinks": false
  },
  "error_file" : "./logs/pm2-err.log",
  "out_file"   : "./logs/pm2-out.log",
  "env": {
    "NODE_ENV": "production"
  },
  "args": [
    "--color"
  ]
}

```

Dockerfile
```Dockerfile
FROM node:10.16.3-slim

WORKDIR /app

COPY . /app/

RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN cnpm install pm2 -g
RUN cnpm install

EXPOSE 3333

CMD ["pm2-runtime", "ecosystem.config.js"]
```
.dockerignore
```gitignore
node_modules/*
logs/*
.idea/*
.git/*

```
编译镜像, 运行容器
```bash
$ docker build -t cloud-component-compiler:v1 .
$ docker run -d -p 3333:3333 --name="cloud-component-compiler" --restart=always \
  -v /mnt/www/cloud-ui/cloud-component-compiler/public:/app/public \
  -v /mnt/www/cloud-ui/cloud-component-compiler/logs:/app/logs \
  cloud-component-compiler:v1
# $ docker logs -f cloud-component-compiler # 可以查看日志
```
nginx配置: `/etc/nginx/sites-enabled/cloud-component-compiler.conf`
```nginx
upstream nodejs_upstream {
    server 127.0.0.1:7001;
    keepalive 64;
}

server {
    listen 80;
    server_name node.cloud-ui.zezeping.com;
    # root /home/www/project_root;
    
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_max_temp_file_size 0;
        proxy_pass http://nodejs_upstream/;
        proxy_redirect off;
        proxy_read_timeout 240s;
    }
}
```
重启nginx: `sudo service nginx reload`

---
### Rails部署
* 创建`Dockerfile`
```Dockerfile
FROM ruby:2.7.1-slim

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

# 设置环境变量，即在后面可以用 $RAILS_ROOT
# 来指代容器中的 rails 程序放的目录
ENV RAILS_ROOT /app

# WORKDIR /app
WORKDIR $RAILS_ROOT

COPY . ./

# Ruby 使用的是 Debian 系统
# 刷新 debian 的软件管理源，否则，慢得让人抓狂
# Ruby 使用的是 Debian 系统
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
     echo "deb http://mirrors.ustc.edu.cn/debian stable main contrib non-free" >/etc/apt/sources.list && \
     echo "deb http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free" >>/etc/apt/sources.list

# 更改默认GEM源
RUN gem sources -r https://rubygems.org/ && gem sources -a https://gems.ruby-china.com/

# 安装必要套件
RUN apt update
RUN apt-get update -qq && apt-get install -y build-essential nodejs git default-libmysqlclient-dev 
# postgresql-client sqlite3 --no-install-recommends

# 安装 Rails 环境
RUN gem install bundler
RUN bundle install

RUN mkdir -p $RAILS_ROOT/tmp/pids

# 比较重要的一步，对静态资源进行 precompile
# RUN bundle exec rake assets:precompile RAILS_ENV=production

# puma
EXPOSE 3000

CMD ["bundle", "exec", "puma", "-C", "config/puma_docker.rb"]
```
* 创建`config/puma_docker.rb`
```ruby
# puma_docker.rb:

threads 4, 16
workers 2
environment 'production'
bind 'tcp://0.0.0.0:3000'
preload_app!

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```
创建`.dockerignore`
```gitignore
.git
```
`config/puma_docker.rb`
```ruby
threads 4, 16
workers 2
environment 'production'
bind 'tcp://0.0.0.0:3000'
preload_app!

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```
创建`docker-compose.yml`
```yaml
version: '3'
services:
  app:
    container_name: cloud-service
    image: cloud-service:v1
    environment:
      RAILS_ENV: production
    ports:
      - "7002:3000"
    volumes:
      - /mnt/www/cloud-ui/cloud-service/log:/app/log
      - /mnt/www/cloud-ui/cloud-service/public:/app/public
      - /mnt/www/cloud-ui/cloud-service/storage:/app/storage
    depends_on:
      # - redis
      - mysql
  # redis:
  #   image: redis:6.0.6-alpine
  #   container_name: redis
  #   ports:
  #     - "7379:6379"

  mysql:
    image: mysql:5.7.27
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root@mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@mysql
    ports:
      - "7306:3306"
    volumes:
      - "/mnt/volumes/mysql/data:/var/lib/mysql"
      - "/mnt/volumes/mysql/conf:/etc/mysql/conf.d"
```
执行命令:
```bash
# 创建app镜像
$ sudo docker build -t cloud-service:v1 .
# 通过docker-compose启动镜像
$ sudo docker-compose up -d
```
